### ISSUE TITLE
go1.6 support

### ISSUE THREAD

**Issue by shanemhansen** [valyala/ybc#13]
It appears the go ybc bindings break the go1.6 cgo rules.

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/valyala/ybc/bindings/go/ybc.(*Cache).GetItem(0xc82000e510, 0xc82000a3a0, 0x3, 0x8, 0xc820012300, 0x0, 0x0)
	/home/shansen/src/github.com/valyala/ybc/bindings/go/ybc/ybc.go:563 +0x409
github.com/valyala/ybc/bindings/go/ybc.(*Cache).Get(0xc82000e510, 0xc82000a3a0, 0x3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/shansen/src/github.com/valyala/ybc/bindings/go/ybc/ybc.go:468 +0x6a
main.main()
	/home/shansen/$snip/main.go:18 +0x13c
exit status 2
```

Source:

```
package main

import (
	"github.com/valyala/ybc/bindings/go/ybc"
)

func main() {
	cfg := &ybc.Config{
		DataFileSize:  ybc.SizeT(10240),
		MaxItemsCount: ybc.SizeT(100),
		IndexFile:     "foo.idx",
		DataFile:      "foo.dat",
	}
	cache, err := cfg.OpenCache(true)
	if err != nil {
		panic(err)
	}
	if _, err = cache.Get([]byte("foo")); err != nil {
		panic(err)
	}

}
```

**Comment by valyala** [comment]
Thanks for the bug report, @shanemhansen ! I'll look into it on the next week.

There was related bug, which had been fixed in go1.2 - see https://code.google.com/p/go/issues/detail?id=6397 .

**Comment by tarndt** [comment]
The draft of the Go 1.6 release notes has more details about the new rules: https://tip.golang.org/doc/go1

**Comment by valyala** [comment]
Fixed

**Comment by tarndt** [comment]
Thanks for fixing!
