### ISSUE TITLE
Cant store json in ybc using golang

### ISSUE THREAD

**Issue by Vektah** [valyala/ybc#14]
Not sure what is going on here...
```
package main

import (
	"encoding/json"
	"github.com/valyala/ybc/bindings/go/ybc"
	"time"
)

func main() {
	cfg := &ybc.Config{
		DataFileSize:  ybc.SizeT(10240),
		MaxItemsCount: ybc.SizeT(100),
		IndexFile:     "foo.idx",
		DataFile:      "foo.dat",
	}
	cache, err := cfg.OpenCache(true)
	if err != nil {
		panic(err)
	}

	b, err := json.Marshal(123)
	if err != nil {
		panic(err)
	}

	if err = cache.Set([]byte("key"), b, time.Hour); err != nil {
		panic(err)
	}
}
```
gives
```
[adam@scopuli ~]$ go run test.go 
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x5123a0, 0xc82000a430)
        /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/valyala/ybc/bindings/go/ybc.(*Cache).Set(0xc82000e2e0, 0xc82000a410, 0x3, 0x8, 0xc820082024, 0x3, 0x40, 0x34630b8a000, 0x0, 0x0)
        /home/adam/go/src/github.com/valyala/ybc/bindings/go/ybc/ybc.go:457 +0x385
main.main()
        /home/adam/test.go:26 +0x226
exit status 2
```

**Comment by valyala** [comment]
This looks like a bug in Go runtime. Will try narrowing down it and posting to Go issue tracker.

**Comment by valyala** [comment]
As a temporary workaround you can use `GODEBUG="cgocheck=0"` environment variable for disabling cgo check. See `Environment Variables` chapter in [runtime](https://golang.org/pkg/runtime/) package for details.

**Comment by valyala** [comment]
Minimized it to:
```go
package main

// static void foo(void *p) {}
import "C"

import (
    "encoding/json"
    "unsafe"
)

func main() {
    b, err := json.Marshal(123)
    if err != nil {
        panic(err)
    }
    p := unsafe.Pointer(&b[0])
    C.foo(p)
}
```

**Comment by valyala** [comment]
There is another workaround mentioned in the linked Go issue:

> What is messing up is that encoding/json uses a 64 byte buffer in a larger struct, and if the encoding requires 64 bytes or fewer than the resulting pointer is into that struct. So one workaround is

```go
if len(b) <= 64 {
    b = append([]byte(nil), b...)
}
if err = cache.Set([]byte("key"), b, time.Hour); err != nil {
        panic(err)
}
```
